// File generated from our OpenAPI spec by Stainless. See CONTRIBUTING.md for details.

package cmd

import (
	"context"
	"fmt"

	"github.com/Increase/increase-cli/internal/apiquery"
	"github.com/Increase/increase-cli/internal/requestflag"
	"github.com/Increase/increase-go"
	"github.com/Increase/increase-go/option"
	"github.com/tidwall/gjson"
	"github.com/urfave/cli/v3"
)

var oauthTokensCreate = cli.Command{
	Name:    "create",
	Usage:   "Create an OAuth Token",
	Suggest: true,
	Flags: []cli.Flag{
		&requestflag.Flag[string]{
			Name:     "grant-type",
			Usage:    "The credential you request in exchange for the code. In Production, this is always `authorization_code`. In Sandbox, you can pass either enum value.",
			Required: true,
			BodyPath: "grant_type",
		},
		&requestflag.Flag[string]{
			Name:     "client-id",
			Usage:    "The public identifier for your application.",
			BodyPath: "client_id",
		},
		&requestflag.Flag[string]{
			Name:     "client-secret",
			Usage:    "The secret that confirms you own the application. This is redundant given that the request is made with your API key but it's a required component of OAuth 2.0.",
			BodyPath: "client_secret",
		},
		&requestflag.Flag[string]{
			Name:     "code",
			Usage:    "The authorization code generated by the user and given to you as a query parameter.",
			BodyPath: "code",
		},
		&requestflag.Flag[string]{
			Name:     "production-token",
			Usage:    "The production token you want to exchange for a sandbox token. This is only available in Sandbox. Set `grant_type` to `production_token` to use this parameter.",
			BodyPath: "production_token",
		},
	},
	Action:          handleOAuthTokensCreate,
	HideHelpCommand: true,
}

func handleOAuthTokensCreate(ctx context.Context, cmd *cli.Command) error {
	client := increase.NewClient(getDefaultRequestOptions(cmd)...)
	unusedArgs := cmd.Args().Slice()

	if len(unusedArgs) > 0 {
		return fmt.Errorf("Unexpected extra arguments: %v", unusedArgs)
	}

	params := increase.OAuthTokenNewParams{}

	options, err := flagOptions(
		cmd,
		apiquery.NestedQueryFormatDots,
		apiquery.ArrayQueryFormatComma,
		ApplicationJSON,
		false,
	)
	if err != nil {
		return err
	}

	var res []byte
	options = append(options, option.WithResponseBodyInto(&res))
	_, err = client.OAuthTokens.New(ctx, params, options...)
	if err != nil {
		return err
	}

	obj := gjson.ParseBytes(res)
	format := cmd.Root().String("format")
	explicitFormat := cmd.Root().IsSet("format")
	transform := cmd.Root().String("transform")
	return ShowJSON(obj, ShowJSONOpts{
		ExplicitFormat: explicitFormat,
		Format:         format,
		RawOutput:      cmd.Root().Bool("raw-output"),
		Title:          "oauth-tokens create",
		Transform:      transform,
	})
}
