// File generated from our OpenAPI spec by Stainless. See CONTRIBUTING.md for details.

package cmd

import (
	"context"
	"fmt"
	"os"

	"github.com/Increase/increase-cli/internal/apiquery"
	"github.com/Increase/increase-cli/internal/requestflag"
	"github.com/Increase/increase-go"
	"github.com/Increase/increase-go/option"
	"github.com/tidwall/gjson"
	"github.com/urfave/cli/v3"
)

var simulationsCardAuthorizationsCreate = requestflag.WithInnerFlags(cli.Command{
	Name:    "create",
	Usage:   "Simulates a purchase authorization on a [Card](#cards). Depending on the balance\navailable to the card and the `amount` submitted, the authorization activity\nwill result in a [Pending Transaction](#pending-transactions) of type\n`card_authorization` or a [Declined Transaction](#declined-transactions) of type\n`card_decline`. You can pass either a Card id or a\n[Digital Wallet Token](#digital-wallet-tokens) id to simulate the two different\nways purchases can be made.",
	Suggest: true,
	Flags: []cli.Flag{
		&requestflag.Flag[int64]{
			Name:     "amount",
			Usage:    "The authorization amount in cents.",
			Required: true,
			BodyPath: "amount",
		},
		&requestflag.Flag[string]{
			Name:     "authenticated-card-payment-id",
			Usage:    "The identifier of a Card Payment with a `card_authentication` if you want to simulate an authenticated authorization.",
			BodyPath: "authenticated_card_payment_id",
		},
		&requestflag.Flag[string]{
			Name:     "card-id",
			Usage:    "The identifier of the Card to be authorized.",
			BodyPath: "card_id",
		},
		&requestflag.Flag[string]{
			Name:     "decline-reason",
			Usage:    "Forces a card decline with a specific reason. No real time decision will be sent.",
			BodyPath: "decline_reason",
		},
		&requestflag.Flag[string]{
			Name:     "digital-wallet-token-id",
			Usage:    "The identifier of the Digital Wallet Token to be authorized.",
			BodyPath: "digital_wallet_token_id",
		},
		&requestflag.Flag[string]{
			Name:     "event-subscription-id",
			Usage:    "The identifier of the Event Subscription to use. If provided, will override the default real time event subscription. Because you can only create one real time decision event subscription, you can use this field to route events to any specified event subscription for testing purposes.",
			BodyPath: "event_subscription_id",
		},
		&requestflag.Flag[string]{
			Name:     "merchant-acceptor-id",
			Usage:    "The merchant identifier (commonly abbreviated as MID) of the merchant the card is transacting with.",
			BodyPath: "merchant_acceptor_id",
		},
		&requestflag.Flag[string]{
			Name:     "merchant-category-code",
			Usage:    "The Merchant Category Code (commonly abbreviated as MCC) of the merchant the card is transacting with.",
			BodyPath: "merchant_category_code",
		},
		&requestflag.Flag[string]{
			Name:     "merchant-city",
			Usage:    "The city the merchant resides in.",
			BodyPath: "merchant_city",
		},
		&requestflag.Flag[string]{
			Name:     "merchant-country",
			Usage:    "The country the merchant resides in.",
			BodyPath: "merchant_country",
		},
		&requestflag.Flag[string]{
			Name:     "merchant-descriptor",
			Usage:    "The merchant descriptor of the merchant the card is transacting with.",
			BodyPath: "merchant_descriptor",
		},
		&requestflag.Flag[string]{
			Name:     "merchant-state",
			Usage:    "The state the merchant resides in.",
			BodyPath: "merchant_state",
		},
		&requestflag.Flag[map[string]any]{
			Name:     "network-details",
			Usage:    "Fields specific to a given card network.",
			BodyPath: "network_details",
		},
		&requestflag.Flag[int64]{
			Name:     "network-risk-score",
			Usage:    "The risk score generated by the card network. For Visa this is the Visa Advanced Authorization risk score, from 0 to 99, where 99 is the riskiest.",
			BodyPath: "network_risk_score",
		},
		&requestflag.Flag[string]{
			Name:     "physical-card-id",
			Usage:    "The identifier of the Physical Card to be authorized.",
			BodyPath: "physical_card_id",
		},
		&requestflag.Flag[map[string]any]{
			Name:     "processing-category",
			Usage:    "Fields specific to a specific type of authorization, such as Automatic Fuel Dispensers, Refund Authorizations, or Cash Disbursements.",
			BodyPath: "processing_category",
		},
		&requestflag.Flag[string]{
			Name:     "terminal-id",
			Usage:    "The terminal identifier (commonly abbreviated as TID) of the terminal the card is transacting with.",
			BodyPath: "terminal_id",
		},
	},
	Action:          handleSimulationsCardAuthorizationsCreate,
	HideHelpCommand: true,
}, map[string][]requestflag.HasOuterFlag{
	"network-details": {
		&requestflag.InnerFlag[map[string]any]{
			Name:       "network-details.visa",
			Usage:      "Fields specific to the Visa network.",
			InnerField: "visa",
		},
	},
	"processing-category": {
		&requestflag.InnerFlag[string]{
			Name:       "processing-category.category",
			Usage:      "The processing category describes the intent behind the authorization, such as whether it was used for bill payments or an automatic fuel dispenser.",
			InnerField: "category",
		},
		&requestflag.InnerFlag[map[string]any]{
			Name:       "processing-category.refund",
			Usage:      "Details related to refund authorizations.",
			InnerField: "refund",
		},
	},
})

func handleSimulationsCardAuthorizationsCreate(ctx context.Context, cmd *cli.Command) error {
	client := increase.NewClient(getDefaultRequestOptions(cmd)...)
	unusedArgs := cmd.Args().Slice()

	if len(unusedArgs) > 0 {
		return fmt.Errorf("Unexpected extra arguments: %v", unusedArgs)
	}

	params := increase.SimulationCardAuthorizationNewParams{}

	options, err := flagOptions(
		cmd,
		apiquery.NestedQueryFormatDots,
		apiquery.ArrayQueryFormatComma,
		ApplicationJSON,
		false,
	)
	if err != nil {
		return err
	}

	var res []byte
	options = append(options, option.WithResponseBodyInto(&res))
	_, err = client.Simulations.CardAuthorizations.New(ctx, params, options...)
	if err != nil {
		return err
	}

	obj := gjson.ParseBytes(res)
	format := cmd.Root().String("format")
	explicitFormat := cmd.Root().IsSet("format")
	transform := cmd.Root().String("transform")
	return ShowJSON(os.Stdout, os.Stderr, "simulations:card-authorizations create", obj, format, explicitFormat, transform)
}
