#!/usr/bin/env bash

set -euo pipefail

cd "$(dirname "$0")/.."

# Mark the necessary Go modules as private to avoid Go's proxy
export GOPRIVATE="${GOPRIVATE:+$GOPRIVATE,}github.com/Increase/increase-go,github.com/stainless-sdks/increase-go"

echo "==> Building increase"
go build ./cmd/increase
